baseURL = "https://www.raduciurca.com/"
languageCode = "en-us"
title = "Radu Ciurca 🦄"
theme = "kube"
description = "Radu Ciurca 🦄 The place where I keep track of the proffesional and personal"
Paginate = 4
disqusShortname = "raduciurca"
googleAnalytics = "UA-142872866-1"
images = "https://images.unsplash.com/photo-1413745094207-a01b234cc32f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1489&q=80"
[Params]
  RSSLink = "/index.xml"
  author = "Radu Ciurca" # add your company name
  github = "ciurca" # add your github profile name
  twitter = "radu_ciurca" # add your twitter profile
  email = "raduciurca@gmail.com"
  
[[menu.main]]
    name = "Docs"
    weight = -100
    url = "/docs/"
[[menu.main]]
    name = "Blog"
    weight = -100
    url = "/blog/"
[[menu.main]]
    name = "Faq"
    weight = -100
    url = "/faq/"
[[menu.second]]
  [Params.seo.webmaster_verifications]
      google = "FtdJW4VlfO6hSozwyVRKPxTYIJ_1nEZbWaEB-BYRnMo" # Optional, Google verification code
      bing = "c423c8f620f74725866a2b079454f54c" # Optional, Bing verification code
      alexa = "" # Optional, Alexa verification code
      yandex = "" # Optional, Yandex verification code
