baseURL = "https://raduciurca.com"
languageCode = "en"
defaultContentLanguage = "en"
title = "Radu Ciurca"
theme = "hallo"
disableKinds = ["page", "section", "taxonomy", "taxonomyTerm"]

[Author]
    name = "Radu Ciurca"

[params]

    [[params.links]]
        iconset = "fas"
        icon = "envelope"
        title = "E-mail"
        url = "mailto:raduciurca@gmail.com"

    [[params.links]]
        icon = "linkedin"
        title = "LinkedIn"
        url = "https://www.linkedin.com/in/raduciurca"
